config/routes.rb
Rails.application.routes.draw do
  
  resources :genres

  get 'signin' => "sessions#new"
  resource :session
  
  get 'signup' => "users#new"
  resources :users

  root "movies#index"
  # get "movies/filter/hits" => "movies#index", scope: "hits"
  # get "movies/filter/flops" => "movies#index", scope: "flops"
  # get "movies/filter/:scope" => "movies#index", as: :filtered_movies
  get 'movies/:scope' => "movies#index", 
    constraints: { scope: /hits|flops|upcoming|recent/ }, as: :filtered_movies
  resources :movies do
    resources :reviews
    resources :favorites
  end
end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="page-footer">
  <p>
    Copyright &copy; 2015
    <%= link_to 'The Pragmatic Studio', 'http://pragmaticstudio.com' %>
  </p>
  <p>
    For educational purposes only.
  </p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
  <div id="masthead">
    <h1><%= link_to 'Flix', root_path %></h1>
    <nav>
    <p>
      <% if current_user %>
        <%= link_to current_user.name, current_user %> |
        <%= link_to "Sign Out", session_path, method: :delete, class: "button" %>
        <%= link_to "Account Setting", edit_user_path(current_user) %>
      <% else %>
        <%= link_to 'Sign up', signup_path, class: "button" %>
        <%= link_to 'Sign In', signin_path, class: "button" %>
      <% end %>
    </p>
  </nav>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
  <nav>
    <ul>
      <li class="all-movies">
        <%= nav_link_to 'Released', movies_path %>
      </li>
      <% if current_user_admin? %>
        <li class="create-movie">
          <%= nav_link_to 'Add New Movie', new_movie_path %>
        </li>
      <% end %>
      <li class="movies">
        <%= nav_link_to 'Hits', filtered_movies_path(:hits) %>
      </li>
      <li class="movies">
        <%= nav_link_to 'Flops', filtered_movies_path(:flops) %>
      </li>
      <li class="movies">
        <%= nav_link_to 'Recent', filtered_movies_path(:recent) %>
      </li>
      <li class="movies">
        <%= nav_link_to 'Upcoming', filtered_movies_path(:upcoming) %>
      </li>
    </ul>
  </nav>
  
    <%= content_for(:side) %>
 
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= page_title %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>

<div id="wrapper">
  
  <%= render "layouts/flashes" %>
  <div id="container">
    <section id="sidebar">
      <%= render "layouts/sidebar" %>
    </section>
    <section id="content">
      <%= yield %>
    </section>
  </div>

</div>

<%= render "layouts/footer" %>

</body>
</html>